### DISCUSSION TITLE
Display driver

### DISCUSSION THREAD

**Discussion by guelz** [xVolta/sensorbox#1] [General]
Thank you for this! It looks great!
I had some issues finding the correct display driver and the screen rotation settings. I thought I have a "ST7735" Model which works with this:
```
display:
  - platform: ili9xxx    
    model: ST7735
    cs_pin: GPIO03
    dc_pin: GPIO04
    reset_pin: GPIO06
    data_rate: 10MHz
    transform:
      swap_xy: true
      mirror_y: true
    color_order: rgb
    invert_colors: false
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      height: 320
      width: 240
```
but the colors and text looked absolutely awful!
So I ended up using this:
```
display:
  - platform: ili9xxx
    model: ILI9341
    cs_pin: GPIO03
    dc_pin: GPIO04
    reset_pin: GPIO06
    data_rate: 10MHz
    rotation: 270°
    color_order: rgb 
    invert_colors: false
    auto_clear_enabled: false
    update_interval: never
    dimensions:
      height: 240
      width: 320
```
colors look very good and the text is crisp and readable this way!

Without  `data_rate:` set I could not even turn or transform the screen! `transform:` does not work in any combination on my screen!
I'm still unsure what screen model I actually got!/
